=== ONSdigital/sds-schema-definitions/schemas/ppi/v3.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "v3.json",
  "title": "SDS schema for the PPI survey",
  "type": "object",
  "properties": {
    "schema_version": {
      "const": "v3",
      "description": "Version of the schema spec"
    },
    "survey_id": {
      "type": "string",
      "description": "The identifier for a particular survey",
      "enum": ["132"]
    },
    "identifier": {
      "type": "string",
      "description": "The unique top-level identifier. For business surveys this is the reporting unit reference without the check letter appended.",
      "minLength": 11,
      "maxLength": 11,
      "pattern": "^[a-zA-Z0-9]+$",
      "examples": ["34942807969"]
    },
    "supplier_number": {
      "type": "string",
      "description": "Like ruref, this is also a unique top-level identifier for the business.",
      "minLength": 1,
      "maxLength": 11,
      "pattern": "^[a-zA-Z0-9]+$",
      "examples": ["34942807969"]
    },
    "current_month": {
      "type": "string",
      "description": "The month and year that the data is required for.",
      "minLength": 8,
      "maxLength": 14,
      "pattern": "^[A-Za-z]+ [0-9]{4}$",
      "examples": ["July 2023"]
    },
    "items": {
      "type": "object",
      "propertyNames": {
        "pattern": "^[a-z0-9][a-z0-9\\-]*[a-z0-9]$"
      },
      "properties": {
        "item": {
          "type": "array",
          "description": "The data about each item",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "object",
            "properties": {
              "identifier": {
                "type": "string",
                "minLength": 10,
                "maxLength": 10,
                "description": "The 10 digit unique reference for each item produced by the business. This number is allocated by ONS, if the item was to change the number would stay the same.",
                "examples": ["3494280796"]
              },
              "supplier_number": {
                "type": "string",
                "description": "Like ruref, this is also a unique top-level identifier for the business.",
                "minLength": 1,
                "maxLength": 11,
                "pattern": "^[a-zA-Z0-9]+$",
                "examples": ["34942807969"]
              },
              "item_number": {
                "type": "string",
                "description": "The 10 digit unique reference for each item produced by the business. This number is allocated by ONS, if the item was to change the number would stay the same.",
                "minLength": 10,
                "maxLength": 10,
                "pattern": "^[a-zA-Z0-9]+$",
                "examples": ["3494280796"]
              },
              "item_specification_1": {
                "type": "string",
                "description": "A separate field of the specification for the item produced by the business, the contents and order of this field can change dependent on the number of characters. This line is always PRODUCT.",
                "minLength": 1,
                "maxLength": 40,
                "examples": ["PRODUCT: HEAT EXCHANGER AIR-AIR"]
              },
              "item_specification_2": {
                "type": "string",
                "description": "A separate field of the specification for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["DESCRIPTION: REFRIGERATION AND FREEZING"]
              },
              "item_specification_3": {
                "type": "string",
                "description": "A separate field of the specification for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["EQUIPMENT AND HEAT PUMPS: EXCEPT"]
              },
              "item_specification_4": {
                "type": "string",
                "description": "A separate field of the specification for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["HOUSEHOLD TYPE EQUIPMENT"]
              },
              "item_specification_5": {
                "type": "string",
                "description": "A separate field of the specification for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["SERIAL NO: 8585C000-001"]
              },
              "unit_of_sale": {
                "type": "string",
                "description": "The unit of sale for the item produced bu the business.",
                "minLength": 1,
                "maxLength": 40,
                "examples": ["EACH"]
              },
              "terms_of_sale_1": {
                "type": "string",
                "description": "A separate field of the terms of sale for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "minLength": 1,
                "maxLength": 40,
                "examples": ["SUPPLIER REF: 123073"]
              },
              "terms_of_sale_2": {
                "type": "string",
                "description": "A separate field of the terms of sale for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["PAYMENT: 60 DAYS NET"]
              },
              "terms_of_sale_3": {
                "type": "string",
                "description": "A separate field of the terms of sale for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["CARRIAGE: FCA"]
              },
              "terms_of_sale_4": {
                "type": "string",
                "description": "A separate field of the terms of sale for the item produced by the business, the contents and order of this field can change dependent on the number of characters.",
                "maxLength": 40,
                "examples": ["TERM: EX WORKS"]
              },
              "currency": {
                "type": "string",
                "description": "The currency which the product price is recorded in.",
                "minLength": 1,
                "maxLength": 25,
                "examples": ["POUND STERLING"]
              }
            },
            "additionalProperties": false,
            "required": [
              "identifier",
              "supplier_number",
              "item_number",
              "item_specification_1",
              "unit_of_sale",
              "terms_of_sale_1",
              "currency"
            ]
          }
        }
      },
      "additionalProperties": false,
      "required": ["item"]
    }
  },
  "additionalProperties": false,
  "required": [
    "schema_version",
    "survey_id",
    "identifier",
    "supplier_number",
    "current_month",
    "items"
  ]
}

=== ONSdigital/sds-schema-definitions/examples/ppi/v3.json
{
  "schema_version": "v3",
  "survey_id": "132",
  "identifier": "12345678901",
  "supplier_number": "23456789012",
  "current_month": "July 2023",
  "items": {
    "item": [
      {
        "identifier": "1234567890",
        "supplier_number": "12345678901",
        "item_number": "1234567890",
        "item_specification_1": "PRODUCT: HEAT EXCHANGER AIR-AIR",
        "item_specification_2": "DESCRIPTION: REFRIGERATION AND FREEZING",
        "item_specification_3": "EQUIPMENT AND HEAT PUMPS: EXCEPT",
        "item_specification_4": "",
        "item_specification_5": "SERIAL NO: 8585C000-001",
        "unit_of_sale": "EACH",
        "terms_of_sale_1": "SUPPLIER REF: 123073",
        "terms_of_sale_2": "PAYMENT: 60 DAYS NET",
        "terms_of_sale_3": "CARRIAGE: FCA",
        "terms_of_sale_4": "TERM: EX WORKS",
        "currency": "POUND STERLING"
      },
      {
        "identifier": "9876543210",
        "supplier_number": "98765432101",
        "item_number": "9876543210",
        "item_specification_1": "PRODUCT: HEAT EXCHANGER WATER-WATER",
        "item_specification_2": "DESCRIPTION: INDUSTRIAL COOLING",
        "item_specification_3": "EQUIPMENT AND HEAT PUMPS: INDUSTRIAL",
        "item_specification_4": "COMMERCIAL TYPE EQUIPMENT",
        "item_specification_5": "SERIAL NO: 1234A567-890",
        "unit_of_sale": "EACH",
        "terms_of_sale_1": "SUPPLIER REF: 987654",
        "terms_of_sale_2": "PAYMENT: 30 DAYS NET",
        "terms_of_sale_3": "",
        "terms_of_sale_4": "TERM: FOB",
        "currency": "EURO"
      }
    ]
  }
}
