=== ONSdigital/sds-schema-definitions/schemas/prodcom.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "prodcom.json",
  "title": "SDS schema for the PRODCOM survey",
  "type": "object",
  "properties": {
    "schema_version": {
      "const": "v1",
      "description": "Version of the schema spec"
    },
    "identifier": {
      "type": "string",
      "description": "The unique top-level identifier. This is the reporting unit reference without the check letter appended.",
      "minLength": 11,
      "pattern": "^[a-zA-Z0-9]+$",
      "examples": ["34942807969"]
    },
    "note": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "description": "The title of the note to be used at the questionnaire or product level",
          "examples": ["Volume of total production"]
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "description": "The description of the note to be used at the questionnaire or product level",
          "examples": [
            "Figures should cover the total quantity of the goods produced during the period of the return - regardless of whether you sold them or not. This includes any production that was incorporated into the manufacture of other products. Exclude goods produced during an earlier period even if you sold them during the period covered by this return."
          ]
        }
      },
      "additionalProperties": false,
      "required": ["title", "description"]
    },
    "items": {
      "type": "object",
      "properties": {
        "products": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "object",
            "properties": {
              "identifier": {
                "type": "string",
                "minLength": 1,
                "description": "The identifier for the product. This is the same as answer code for value of sales.",
                "examples": ["89929001"]
              },
              "name": {
                "type": "string",
                "minLength": 1,
                "description": "The product name",
                "examples": [
                  "Articles and equipment for sports or outdoor games"
                ]
              },
              "cn_codes": {
                "type": "string",
                "minLength": 1,
                "description": "The CN codes for the product",
                "examples": ["2504 + 250610 + 2512 + 2519 + 2524"]
              },
              "guidance_include": {
                "type": "object",
                "description": "Content for the 'Include' guidance panel",
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "The title of the 'Include' panel",
                    "minLength": 1,
                    "examples": ["Include"]
                  },
                  "list": {
                    "type": "array",
                    "description": "A list of bullet points to show on the 'Include' guidance panel",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "type": "string", "minLength": 1 },
                    "examples": [
                      [
                        "for children's playgrounds",
                        "swimming pools and paddling pools"
                      ]
                    ]
                  }
                },
                "additionalProperties": false,
                "required": ["title", "list"]
              },
              "guidance_exclude": {
                "type": "object",
                "description": "Content for the 'Exclude' guidance panel",
                "properties": {
                  "title": {
                    "type": "string",
                    "description": "The title of the 'Exclude' panel",
                    "minLength": 1,
                    "examples": ["Exclude"]
                  },
                  "list": {
                    "type": "array",
                    "description": "A list of bullet points to show on the 'Exclude' guidance panel",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": { "type": "string", "minLength": 1 },
                    "examples": [
                      [
                        "sports holdalls, gloves, clothing of textile materials, footwear, protective eyewear, rackets, balls, skates",
                        "for skiing, water sports, golf, fishing",
                        "for skiing, water sports, golf, fishing, table tennis, PE, gymnastics, athletics"
                      ]
                    ]
                  }
                },
                "additionalProperties": false,
                "required": ["title", "list"]
              },
              "value_sales": {
                "type": "object",
                "description": "Content for the 'Value of Sales' answer",
                "properties": {
                  "answer_code": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The unique answer code for value of sales answer",
                    "examples": ["89929001"]
                  },
                  "label": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The answer label for the value of sales input",
                    "examples": ["Value of sales"]
                  }
                },
                "additionalProperties": false,
                "required": ["answer_code", "label"]
              },
              "volume_sales": {
                "type": "object",
                "description": "Content for the 'Volume of Sales' answer",
                "properties": {
                  "answer_code": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The unique answer code for volume of sales answer",
                    "examples": ["89929002"]
                  },
                  "label": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The answer label for the volume of sales input",
                    "examples": ["Volume of sales"]
                  },
                  "unit_label": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The unit label for the volume of sales input",
                    "examples": ["Kilogram"]
                  }
                },
                "additionalProperties": false,
                "required": ["answer_code", "label", "unit_label"]
              },
              "total_volume": {
                "type": "object",
                "description": "Content for the 'Total Volume Produced' answer",
                "properties": {
                  "answer_code": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The unique answer code for total volume produced answer",
                    "examples": ["89929005"]
                  },
                  "label": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The answer label for the total volume produced input",
                    "examples": ["Total volume produced"]
                  },
                  "unit_label": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The unit label for the total volume produced input",
                    "examples": ["Kilogram"]
                  }
                },
                "additionalProperties": false,
                "required": ["answer_code", "label", "unit_label"]
              }
            },
            "additionalProperties": false,
            "required": ["identifier", "name", "cn_codes", "value_sales"],
            "dependentRequired": {
              "total_volume": ["volume_sales"]
            }
          }
        }
      },
      "additionalProperties": false,
      "required": ["products"]
    }
  },
  "additionalProperties": false,
  "required": ["schema_version", "identifier", "items"]
}

=== ONSdigital/sds-schema-definitions/examples/prodcom/v1.json
{
  "schema_version": "v1",
  "identifier": "79900005222",
  "note": {
    "title": "Volume of total production",
    "description": "Figures should cover the total quantity of the goods produced during the period of the return - regardless of whether you sold them or not. This includes any production that was incorporated into the manufacture of other products. Exclude goods produced during an earlier period even if you sold them during the period covered by this return."
  },
  "items": {
    "products": [
      {
        "identifier": "89929001",
        "name": "Articles and equipment for sports or outdoor games",
        "cn_codes": "2504 + 250610 + 2512 + 2519 + 2524",
        "guidance_include": {
          "title": "Include",
          "list": [
            "for children's playgrounds",
            "swimming pools and paddling pools"
          ]
        },
        "guidance_exclude": {
          "title": "Exclude",
          "list": [
            "sports holdalls, gloves, clothing of textile materials, footwear, protective eyewear, rackets, balls, skates",
            "for skiing, water sports, golf, fishing', for skiing, water sports, golf, fishing, table tennis, PE, gymnastics, athletics"
          ]
        },
        "value_sales": {
          "answer_code": "89929001",
          "label": "Value of sales"
        },
        "volume_sales": {
          "answer_code": "89929002",
          "label": "Volume of sales",
          "unit_label": "Tonnes"
        },
        "total_volume": {
          "answer_code": "89929005",
          "label": "Total volume produced",
          "unit_label": "Tonnes"
        }
      },
      {
        "identifier": "201630601",
        "name": "Other Minerals",
        "cn_codes": "5908 + 5910 + 591110 + 591120 + 591140",
        "guidance_include": {
          "title": "Include",
          "list": [
            "natural graphite",
            "quartz for industrial use",
            "diatomite; magnesia; feldspar",
            "magnesite; natural magnesium carbonate",
            "talc including steatite and chlorite",
            "unexpanded vermiculite and perlite"
          ]
        },
        "guidance_exclude": {
          "title": "Exclude",
          "list": ["natural quartz sands"]
        },
        "value_sales": {
          "answer_code": "201630601",
          "label": "Value of sales"
        },
        "volume_sales": {
          "answer_code": "201630602",
          "label": "Volume of sales",
          "unit_label": "Kilogram"
        },
        "total_volume": {
          "answer_code": "201630605",
          "label": "Total volume produced",
          "unit_label": "Kilogram"
        }
      }
    ]
  }
}
